#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

####################
# links to add
my $event = "nethserver-madsonic-update";

# templates to expand
    templates2events( "/etc/sysconfig/madsonic" , $event);
    templates2events( "/etc/samba/smb.conf" , $event );
    templates2events("/etc/httpd/conf.d/madsonic.conf", $event);

# services to launch on event
event_services($event, 'madsonic' => 'restart');
event_services($event, 'smb' => 'restart');
event_services($event, 'nmb' => 'restart');


# Action to do 
event_actions($event, 
'initialize-default-databases' => '00',
'nethserver-madsonic-httpd-restart' => '95');
event_actions($event,
'firewall-adjust' => '10');
